include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/.dart_tool/**"
  errors:
    invalid_use_of_visible_for_testing_member: warning

linter:
  rules:
    prefer_relative_imports: true
    directives_ordering: true
    always_use_package_imports: false
